#!/usr/bin/env python3

# Copyright 2020 ETH Zurich
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# Author: Robert Balas (balasr@iis.ee.ethz.ch)

# pulpstim
import argparse
import os
import sys
from stim_utils import stim

parser = argparse.ArgumentParser(prog='pulpstim',
                                 description="""Generate stimuli files from ELF
                                 files for the JTAG TAP in PULPissimo""")

parser.version = '0.1'
parser.add_argument('Path', metavar='path',
                    type=str, help='the path to elf file')
parser.add_argument('-o', '--output', metavar='output',
                    type=str, help='the output file name')
parser.add_argument('--verbose', action='store_true',
                    help='enable verbose output')

args = parser.parse_args()
elf_file = args.Path

if not os.path.isfile(elf_file):
    print('The specified path does not exist')
    sys.exit(1)

stimuli_generator = stim(args.verbose)
stimuli_generator.add_binary(elf_file)
stimuli_generator.gen_stim_slm_64(args.output if args.output else 'stim.txt')
